<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ServiceDefaults\AspireQuotesPoc.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
