// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quotes.Infrastructure.Persistence;

#nullable disable

namespace Quotes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    partial class QuotesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quotes.Infrastructure.Persistence.QuoteRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedFingerprint")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFingerprint")
                        .IsUnique();

                    b.ToTable("quotes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Author = "Leonardo da Vinci",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "simplicity is the ultimate sophistication",
                            Text = "Simplicity is the ultimate sophistication."
                        },
                        new
                        {
                            Id = "2",
                            Author = "Cory House",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "code is like humor when you have to explain it it s bad",
                            Text = "Code is like humor. When you have to explain it, it's bad."
                        },
                        new
                        {
                            Id = "3",
                            Author = "John Johnson",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "first solve the problem then write the code",
                            Text = "First, solve the problem. Then, write the code."
                        },
                        new
                        {
                            Id = "4",
                            Author = "Oscar Wilde",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "experience is the name everyone gives to their mistakes",
                            Text = "Experience is the name everyone gives to their mistakes."
                        },
                        new
                        {
                            Id = "5",
                            Author = "Robert C. Martin",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "the only way to go fast is to go well",
                            Text = "The only way to go fast is to go well."
                        },
                        new
                        {
                            Id = "6",
                            Author = "Kent Beck",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "make it work make it right make it fast",
                            Text = "Make it work, make it right, make it fast."
                        },
                        new
                        {
                            Id = "7",
                            Author = "Harold Abelson",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "programs must be written for people to read",
                            Text = "Programs must be written for people to read."
                        },
                        new
                        {
                            Id = "8",
                            Author = "Linus Torvalds",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedFingerprint = "talk is cheap show me the code",
                            Text = "Talk is cheap. Show me the code."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
