/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/quotes/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a random quote from the catalog.
         * @description Requires a bearer JWT issued by the Auth API with the `quotes:read` scope
         *     (`POST /api/v1/auth/login`); a valid token without the scope answers 403. The
         *     catalog boots seeded (eight quotes), so 404 here means the catalog was emptied, not
         *     that it has not been filled yet. Send `X-Correlation-Id` to correlate calls; it
         *     is echoed on every response and embedded in problem details.
         */
        get: operations["GetRandomQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists one page of the quote catalog in stable order.
         * @description Requires a bearer JWT issued by the Auth API with the `quotes:read` scope
         *     (`POST /api/v1/auth/login`); a valid token without the scope answers 403.
         *     Pagination is 1-based: `page` starts at 1 and `pageSize` is capped at 100
         *     (default 20); values outside those ranges answer 400 with
         *     `quote.invalid_page_request`. Pages beyond the last return an empty
         *     `items` array, not an error. Send `X-Correlation-Id` to correlate calls;
         *     it is echoed on every response and embedded in problem details.
         */
        get: operations["ListQuotes"];
        put?: never;
        /**
         * Adds a quote to the catalog.
         * @description Requires a bearer JWT issued by the Auth API with the `quotes:write` scope
         *     (`POST /api/v1/auth/login`); read-only tokens answer 403. Catalog rules beyond
         *     the schema limits: text between 12 and 280 characters with at least 3 words, ending
         *     with '.', '!' or '?'; author between 2 and 80 characters (letters, spaces, hyphens,
         *     apostrophes and periods) and different from the text. Near-duplicates (same
         *     fingerprint, for example only punctuation changed) answer 409. The 201 response
         *     carries the created quote and a `Location` header addressing it. Send
         *     `X-Correlation-Id` to correlate calls; it is echoed on every response and
         *     embedded in problem details.
         */
        post: operations["CreateQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns one quote by id.
         * @description Requires a bearer JWT issued by the Auth API with the `quotes:read` scope
         *     (`POST /api/v1/auth/login`); a valid token without the scope answers 403. Ids
         *     come from create responses and list items. Send `X-Correlation-Id` to
         *     correlate calls; it is echoed on every response and embedded in problem details.
         */
        get: operations["GetQuoteById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "text": "Talk is cheap. Show me the code.",
         *       "author": "Linus Torvalds"
         *     }
         */
        CreateQuoteRequestDto: {
            /** @description Quote body text. */
            text: string;
            /** @description Attributed author of the quote. */
            author: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        /**
         * @example {
         *       "items": [
         *         {
         *           "id": "3f2b8a9c1d4e5f6a7b8c9d0e1f2a3b4c",
         *           "text": "Talk is cheap. Show me the code.",
         *           "author": "Linus Torvalds"
         *         }
         *       ],
         *       "page": 1,
         *       "pageSize": 20,
         *       "totalItems": 1,
         *       "totalPages": 1
         *     }
         */
        QuotePageResponseDto: {
            /** @description Quotes on this page, in stable catalog order. */
            items: components["schemas"]["QuoteResponseDto"][];
            /**
             * Format: int32
             * @description 1-based page number this response represents.
             */
            page: number | string;
            /**
             * Format: int32
             * @description Number of items per page that was requested.
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description Total number of quotes in the catalog.
             */
            totalItems: number | string;
            /**
             * Format: int32
             * @description Total number of pages at the requested page size.
             */
            totalPages: number | string;
        };
        /**
         * @example {
         *       "id": "3f2b8a9c1d4e5f6a7b8c9d0e1f2a3b4c",
         *       "text": "Talk is cheap. Show me the code.",
         *       "author": "Linus Torvalds"
         *     }
         */
        QuoteResponseDto: {
            /** @description Stable quote identifier. */
            id: string;
            /** @description Quote body text. */
            text: string;
            /** @description Attributed author of the quote. */
            author: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetRandomQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A random quote. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponseDto"];
                };
            };
            /** @description Missing or invalid bearer token (errorCode `auth.token_missing` or `auth.token_invalid`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.2",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "A valid bearer token is required.",
                     *       "errorCode": "auth.token_invalid",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The token lacks the `quotes:read` scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.4",
                     *       "title": "Forbidden",
                     *       "status": 403,
                     *       "detail": "The access token is missing the required scope (quotes:read or quotes:write)."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The catalog is empty (errorCode `quote.not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.5",
                     *       "title": "Not Found",
                     *       "status": 404,
                     *       "detail": "Quote not found.",
                     *       "errorCode": "quote.not_found",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListQuotes: {
        parameters: {
            query?: {
                /**
                 * @description 1-based page number (minimum 1).
                 * @example 2
                 */
                page?: number | string;
                /**
                 * @description Items per page, between 1 and 100 (default 20).
                 * @example 20
                 */
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page as `{ items, page, pageSize, totalItems, totalPages }`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotePageResponseDto"];
                };
            };
            /** @description Page or pageSize outside the allowed range (errorCode `quote.invalid_page_request`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
                     *       "title": "One or more validation errors occurred.",
                     *       "status": 400,
                     *       "errorCode": "quote.invalid_page_request",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27",
                     *       "errors": {
                     *         "quote.invalid_page_request": [
                     *           "The requested page or page size is outside the allowed range."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Missing or invalid bearer token (errorCode `auth.token_missing` or `auth.token_invalid`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.2",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "A valid bearer token is required.",
                     *       "errorCode": "auth.token_invalid",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The token lacks the `quotes:read` scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.4",
                     *       "title": "Forbidden",
                     *       "status": 403,
                     *       "detail": "The access token is missing the required scope (quotes:read or quotes:write)."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The quote text and its author. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuoteRequestDto"];
            };
        };
        responses: {
            /** @description Quote created; the `Location` header addresses the new quote. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponseDto"];
                };
            };
            /** @description Catalog rule violation (errorCode `quote.text_too_short`, `quote.text_too_long`, `quote.text_needs_more_words`, `quote.text_must_end_with_punctuation`, `quote.author_too_short`, `quote.author_too_long`, `quote.author_invalid_characters` or `quote.author_equals_text`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
                     *       "title": "One or more validation errors occurred.",
                     *       "status": 400,
                     *       "errorCode": "quote.text_too_short",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27",
                     *       "errors": {
                     *         "quote.text_too_short": [
                     *           "Quote text must be at least 12 characters."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Missing or invalid bearer token (errorCode `auth.token_missing` or `auth.token_invalid`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.2",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "A valid bearer token is required.",
                     *       "errorCode": "auth.token_invalid",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The token lacks the `quotes:write` scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.4",
                     *       "title": "Forbidden",
                     *       "status": 403,
                     *       "detail": "The access token is missing the required scope (quotes:read or quotes:write)."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A quote with the same meaning already exists (errorCode `quote.duplicate_fingerprint`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.10",
                     *       "title": "Conflict",
                     *       "status": 409,
                     *       "detail": "A quote with the same meaning already exists.",
                     *       "errorCode": "quote.duplicate_fingerprint",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetQuoteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Quote identifier as returned by create or list.
                 * @example 3f2b8a9c1d4e5f6a7b8c9d0e1f2a3b4c
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested quote. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponseDto"];
                };
            };
            /** @description Missing or invalid bearer token (errorCode `auth.token_missing` or `auth.token_invalid`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.2",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "A valid bearer token is required.",
                     *       "errorCode": "auth.token_invalid",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The token lacks the `quotes:read` scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.4",
                     *       "title": "Forbidden",
                     *       "status": 403,
                     *       "detail": "The access token is missing the required scope (quotes:read or quotes:write)."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No quote matches the id (errorCode `quote.not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://tools.ietf.org/html/rfc9110#section-15.5.5",
                     *       "title": "Not Found",
                     *       "status": 404,
                     *       "detail": "Quote not found.",
                     *       "errorCode": "quote.not_found",
                     *       "correlationId": "5c1f4a0e9d2b7386a4c0b1e8d3f69a27"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
